dist: xenial
language: node_js
node_js:
  - "node"
script:
  - npm install
  - npm run build
  - npm run doc
  - mv out dist/
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: dist
    on:
      branch: master
  - provider: surge
    skip-cleanup: true
    local-dir: dist
    on:
      branch: master
    project: ./dist/
    domain: paperui-ng.surge.sh
